# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# .NET CLI: https://docs.microsoft.com/dotnet/core/tools/
# Description: The purpose of this build is to build and test on both Windows and Linux.

name: Build And Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        framework: [netcoreapp3.1,net5.0]
        include: 
            - os: ubuntu-latest
              args: "--filter TestCategory!=WindowsOnly"

    steps:
    - uses: actions/checkout@v2

    - name: restore (Base sln)
      run: dotnet restore ./BASE/Microsoft.ApplicationInsights.sln

    - name: Build
      run: dotnet build ./BASE/Microsoft.ApplicationInsights.sln --configuration Release --no-restore

    - name: Test
      id: test1
      continue-on-error: true
      run: dotnet test ./BASE/Microsoft.ApplicationInsights.sln --framework ${{ matrix.framework }} --configuration Release --no-build --logger:"console;verbosity=detailed" ${{ matrix.args }}


    - name: Test (retry)
      id: test2
      continue-on-error: true
      if: steps.test1.outcome=='failure'
      run: dotnet test ./BASE/Microsoft.ApplicationInsights.sln --framework ${{ matrix.framework }} --configuration Release --no-build --logger:"console;verbosity=detailed" ${{ matrix.args }}

    - name: Test Status
      if: always()
      run: |
        if ${{ steps.test1.outcome=='success' || steps.test2.outcome=='success' }}; then
            echo fine
        else
            exit 1
        fi